### ISSUE TITLE
progress and status are not updating

### ISSUE THREAD

**Issue by BTMuli** [moham96/torrent_task#17]
Here's my code: [rss_download_card.dart](https://github.com/BTMuli/BangumiToday/blob/e37a3795875b197c3928f80d9dc0605046448230/lib/components/app/rss_dowload_card.dart)

When load widget，the progress is 0,and when run `freshProgess`，the progress is still `0`.

~~May be my code is somewhere wrong~~

![image](https://github.com/moham96/dtorrent_task/assets/72692909/57a4f522-92aa-4798-a02f-327a1b4792b5)

**Comment by BTMuli** [comment]
It seems strange that the currentDownload speed and progress is not sync,which looks that it will update the progress after downloaded.

**Comment by moham96** [comment]
could you test using the `optimization` branch

**Comment by BTMuli** [comment]
> could you test using the `optimization` branch

It seems works well,but some data is zero still(utpUploadSpeed & utpDownloadSpeed)and the last 1% cost much time than the before 99%.

**Comment by moham96** [comment]
> > could you test using the `optimization` branch
> 
> It seems works well,but some data is zero still(utpUploadSpeed & utpDownloadSpeed)and the last 1% cost much time than the before 99%.

Both are expected since
1- utp is broken and disabled right now
2- endgame mode is not optimized

**Comment by BTMuli** [comment]
It freeze my AndroidStudio and app when hot reload,the cpu and memory usage is too high.😭

**Comment by BTMuli** [comment]
> It freeze my AndroidStudio and app when hot reload,the cpu and memory usage is too high.😭

And after I kill it by task manager,it still log in terminal.`[_TCPPeer] null`

**Comment by moham96** [comment]
please test with the latest release 0.4.0 and report back,
note that you don't need to add a periodic timer, just listen to `StateFileUpdated` and similar events here https://github.com/moham96/dtorrent_task/blob/main/lib/src/task_events.dart

look here for an example: https://github.com/moham96/dtorrent_task/blob/main/bin/dtorrent_task.dart

**Comment by BTMuli** [comment]
It works certainly better than before,but still throw err in some case:

```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (length): Invalid value: Not in inclusive range 0..576460752303423487: -40608
#0      new _List.filled (dart:core-patch/array.dart)
#1      UTPSocketImpl.newSelectiveACK (package:utp_protocol/src/utp_socket_impl.dart:851:19)
#2      UTPSocketImpl.sendPacket (package:utp_protocol/src/utp_socket_impl.dart:1006:26)
#3      UTPSocketImpl.requestSendAck.<anonymous closure> (package:utp_protocol/src/utp_socket_impl.dart:881:12)
#4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by moham96** [comment]
> It works certainly better than before,but still throw err in some case:
> 
> ```dart
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (length): Invalid value: Not in inclusive range 0..576460752303423487: -40608
> #0      new _List.filled (dart:core-patch/array.dart)
> #1      UTPSocketImpl.newSelectiveACK (package:utp_protocol/src/utp_socket_impl.dart:851:19)
> #2      UTPSocketImpl.sendPacket (package:utp_protocol/src/utp_socket_impl.dart:1006:26)
> #3      UTPSocketImpl.requestSendAck.<anonymous closure> (package:utp_protocol/src/utp_socket_impl.dart:881:12)
> #4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
> #5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
> #6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
> #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
> ```

yeah unfortunately this is a flaky bug that appeared after i enabled utp, maybe i should disable utp again untill it is stable

**Comment by moham96** [comment]
> It looks like downloading the same file multiple times doesn't seem discerning.🤔 ![image](https://private-user-images.githubusercontent.com/72692909/326954739-76713140-3a1d-48fc-b079-d872470edbcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTUxMDYsIm5iZiI6MTcxNDU1NDgwNiwicGF0aCI6Ii83MjY5MjkwOS8zMjY5NTQ3MzktNzY3MTMxNDAtM2ExZC00OGZjLWIwNzktZDg3MjQ3MGVkYmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA5MTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZTJlZjdiMTdjNGZmZmQ4ZjRhY2U3YWIzOThlOWFjYTJiMDdiNzAxZDNmMTg3YTZkMzFlMjEzOGFmYWJkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MctTr-SaO0gosHJDQi8lte_A1aSPYGYDrtVz2sXzdJg)
hmmmm, maybe we need to `lock` the files when downloading

**Comment by BTMuli** [comment]
Btw,when is download completed
![5073489c38990e54ccae821983b70d84](https://github.com/moham96/dtorrent_task/assets/72692909/f1199378-d10e-44b7-bb39-48c88174a0c2)

Is there any exposed data that can be used to view the progress of file writes?

**Comment by moham96** [comment]
`TaskFileCompleted` should fire when a file inside the torrent is completed and validated and `TaskCompleted` should fire when all the files are complete

**Comment by BTMuli** [comment]
> endgame mode is not optimized

When will it be perfected?Not only is the last 1% download extremely slow, but the 100% to taskComplete is also taking a long time😣

**Comment by moham96** [comment]
> > endgame mode is not optimized
> 
> When will it be perfected?Not only is the last 1% download extremely slow, but the 100% to taskComplete is also taking a long time😣

I'm sorry for the inconvenience, but in case this was not stated before: this project is in alpha state(even though the version numbers don't indicate so) and i have very limited time to work on it, PRs are very welcome
